---
type: service_template
subtype: container
name: nodejs-example
description: nodejs example
container:
  resources:
    mem_mib: 256 
    cpu_cores: 0.1 
    disk_gb: 0
  image: "docker.local/hkmconsultingllc/centos:7"
  docker_options: ''
  command: "%%CMD%%"
inputs:
  artifacts:
  - from: "%%service.checkout_id.code%%"
    path: "/opt/app/systemProps"
  parameters:
    CMD: {}
outputs:
  artifacts:
    code:
      path: "/opt/app/systemProps"

---
type: service_template
subtype: workflow
name: build
description: hkmbuild example workflow
inputs:
  parameters:
    commit:
      default: "%%session.commit%%"
    repo:
      default: "%%session.repo%%"
steps:
- checkout:
    template: hkmcheckout
- build:
    template: nodejs-example
    parameters:
       CMD: "sh -c 'cd /opt/app/systemProps && node index.js'"
       checkout_id: "%%service.checkout.id%%"
